[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
